server:
  port: 9000
spring:
  application:
    name: AWS-KINESIS-CONSUMER-SERVICE
  cloud:
    stream:
      bindings:
        processOrder-in-0:
          destination: test_stream_100
          content-type: application/json
          group: group100
      function:
        definition: processOrder
      kinesis:
        binder:
          kpl-kcl-enabled: true

originator: aws-consumer-service
management:
  endpoints:
    web:
      exposure:
        include: '*'
